language: cpp
compiler: gcc
sudo: required
dist: trusty
os:
- linux
env:
  global:
  - TRAVISCI=true
branches:
- master
- refactor
install:
- sudo add-apt-repository -y ppa:beineri/opt-qt532-trusty && sudo apt-get -qq update
  && sudo apt-get -qq install qt53base qt53serialport
script:
- mkdir build && cd build && cmake .. && make -j4
notifications:
  slack:
    rooms:
      secure: WoW6ygyn6t1cf5dYyuGZps3V4J0My8+uy6KK9OlCyAhzWwmUa1HobXM5+n8JmjwUTRyHO21wLT7JKIE8/VqtrUdZOYvs89NmUqlozzq0h5bY9aYZCb9YlHtUPv4DdwGUZfNagw3kxq2oGBkGA7UxcCvClRIiaahGoLBmG90y1HKUbrV7SSHkJIKEaE4nnqxhBefH42ZkNfxlbVYEvsMi74qkYTPfnY6jBE4YBBCC/lCQ/nPRMhxItd18dK5IflrJJH5GTE+6P2MAYIgQVULCVLsbJEcFBmLlx9P678Qfz6IZCljPzHwKXnrc2LSjrQv71HsKbYHZuLvIgx7udQvGVuhf5jcxgiMxo89WeCKzntfWELkuwDS0QCcza0/g8AFEzsOnjKgdA+uav+Pt5uB73za80IznxJU4yWtX8ZXtrqZaLp/AJCesvfgEQqBin7dZ4yeb/16CoL3A4wLjrxGIvE1Pa/3gD24pDY8/0lBg84CuZsGQOXtC9YNECM17xNPl2qP3lnO9QFaL9+CeN8R7b4rnqugnjeuB/12Cf1OT7HH9m5wBhaXmBKChGHMxih8UXz6egxes0KENR+RF+LIhyGMezuBhZjhdpauzssl3NUzvk91BJQyZ7hU6TYs1EuFxcPuw3DR6hWAeOa8+jjUBuxmyrnljV3ln2ZzKJwGQFWM=
